# Generated by Django 4.1.7 on 2023-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpage',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
