# Generated by Django 4.1.7 on 2023-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_registrationpage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpage',
            name='mobile_no',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
